import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../../widgets/HMBVideoPickerLibraryWidget_v032.js', import.meta.url), 'utf8');
const widget = await import('data:text/javascript;base64,' + Buffer.from(source + '\nexport { outlinerHtml };').toString('base64'));
const settings = widget.hmbNormalizeDepthSettings;
assert.deepEqual(settings(null), {range:'close',expanded_roots:[]});
for (const range of ['close','middle','far']) assert.equal(settings({range}).range, range);
assert.equal(settings({range:'custom'}).range, 'close');
const children = Array.from({length:500}, (_,i) => ({name:'Mesh'+i,full_path:'|Root|Mesh'+i,maya_uuid:'mesh'+i,node_kind:'mesh',parent_path:'|Root'}));
const state = {outliner_nodes:[{name:'Root',full_path:'|Root',maya_uuid:'root',depth_meshes:children,child_count:0}],
  outliner_expanded:[], outliner_search:'',depth_settings:settings(null),slot_assignments:[],slot_visibility:[{video_slot:1,hidden_paths:[]}]};
assert.equal(widget.hmbPickerOutlinerWindow(state,0,500).total,1);
state.depth_settings.expanded_roots=['|Root'];
const windowed = widget.hmbPickerOutlinerWindow(state,0,500);
assert.equal(windowed.total,501);
assert.ok(windowed.virtualized && windowed.nodes.length < 100);
state.selected_outliner_path='|Root|Mesh3'; state.selected_outliner_uuid='mesh3';
assert.equal(widget.hmbPickerSelectedOutlinerNode(state).full_path,'|Root|Mesh3');
state.slot_assignments=[{video_slot:1,bindings:[{full_dag_path:'|Root|Mesh3',maya_uuid:'mesh3',color:'Red'}]}];
assert.equal(widget.hmbEnsurePickerOutlinerSelection(state).selected_color,'Red');
const tr={outliner:'Outliner',noPreviewTitle:'',noPreviewBody:'',reference:'ref',expandNode:'Expand',collapseNode:'Collapse',outputOn:'On',outputOff:'Off',depthPass:'Mesh'};
let markup=widget.outlinerHtml(state,state.slot_assignments[0].bindings,tr);
assert.match(markup,/data-group-path="\|Root\|Mesh3"/);
assert.match(markup,/data-visibility-path="\|Root\|Mesh3"/);
assert.match(markup,/assigned-chip/);
assert.doesNotMatch(markup,/data-depth-mesh-path/);
state.slot_visibility[0].hidden_paths=['|Root'];
markup=widget.outlinerHtml(state,[],tr);
assert.match(markup,/data-inherited-hidden="true"/);
const panel={},control={};
const container={querySelector(s){return s==='.depth-range-settings'?panel:s==='#depth-distance-range'?control:null;}};
widget.hmbApplyPickerOutputChoicesToDom(container,{depth_enabled:false});assert.equal(panel.hidden,true);
widget.hmbApplyPickerOutputChoicesToDom(container,{depth_enabled:true},true);assert.equal(panel.hidden,false);assert.equal(control.disabled,true);
assert.match(source,/depth_settings: hmbNormalizeDepthSettings\(currentLocal.depth_settings\)/);
assert.match(source,/const node = hmbPickerAllOutlinerNodes\(liveState\)/);
console.log('Picker child mesh palette, eye, windowing and conditional Depth UI: PASS');
