import assert from "node:assert/strict";
import fs from "node:fs";

const widgetPath = new URL(
  "../../widgets/HMBVideoPickerLibraryWidget_v032.js",
  import.meta.url,
);
const widgetSource = fs.readFileSync(widgetPath, "utf8");
const widget = await import(
  `data:text/javascript;base64,${Buffer.from(widgetSource).toString("base64")}`
);

const shotUuid = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const asset = (uid) => ({
  video_uid: uid,
  source_uid: uid,
  video_path: `/external/${uid}.mp4`,
  label: uid,
  start_frame: 101,
  end_frame: 148,
  source_fps: 24,
});
const loaderState = (previewUid = "video-a") => ({
  shot_uuid: shotUuid,
  shot_number: 1,
  shot_name: "Shot 1",
  videos: [asset("video-a"), asset("video-b")],
  picker_shots: [{
    workspace_uuid: shotUuid,
    bound_shot_uuid: "",
    number: 1,
    name: "Shot 1",
    video_asset_uids: ["video-a", "video-b"],
    selected_video_uids: ["video-a", "video-b"],
    preview_video_uid: previewUid,
  }],
  active_picker_shot_uuid: shotUuid,
  preview_video_uid: previewUid,
  selected_video_uid: previewUid,
  viewport_mode: "video",
  source_fps: 24,
  current_frame: 101,
});

// Compact and expanded are two presentations of one Loader contract. Compact
// cards expose the same name-selection and native drag surfaces, while their
// posters are images generated by one lazy probe—not one decoder per card.
const compactMarkup = widget.hmbRenderVideoPickerShotWorkspace(
  loaderState(),
  undefined,
  false,
  "compact",
).tabs;
assert.match(compactMarkup, /class="compact-video-select-label"[^>]*role="button"/);
assert.match(compactMarkup, /class="compact-shot-slot compact-shot-asset selected"/);
assert.match(compactMarkup, /draggable="true"/);
assert.equal((compactMarkup.match(/class="compact-video-poster"/g) || []).length, 2);
assert.equal((compactMarkup.match(/data-compact-thumbnail-source=/g) || []).length, 2);
assert.doesNotMatch(compactMarkup, /<video\b/);
const serverPosterState = loaderState();
serverPosterState.videos[0].thumbnail_url = "https://static.invalid/video-a-poster.png";
const serverPosterMarkup = widget.hmbRenderVideoPickerShotWorkspace(
  serverPosterState,
  undefined,
  false,
  "compact",
).tabs;
assert.match(
  serverPosterMarkup,
  /data-compact-thumbnail-poster="https:\/\/static\.invalid\/video-a-poster\.png"/,
);
assert.match(
  serverPosterMarkup,
  /class="compact-video-poster"[^>]*src="https:\/\/static\.invalid\/video-a-poster\.png"/,
  "A backend poster must paint immediately without opening a card decoder.",
);
assert.match(widgetSource, /const cache = new Map\(\);[\s\S]*let probe = null;/);
assert.doesNotMatch(widgetSource, /URL\.createObjectURL|URL\.revokeObjectURL/);
assert.match(
  widgetSource,
  /const toggleSharedLoaderVideoSelection = \(event, selectionSurface\) =>/,
);
assert.equal(
  (widgetSource.match(/toggleSharedLoaderVideoSelection\(event, selectionSurface\);/g) || []).length,
  2,
  "Compact and expanded name clicks must call the same Loader selection contract.",
);
assert.equal(
  (widgetSource.match(/commitState: commitSharedLoaderVideoDrag/g) || []).length,
  2,
  "Compact and expanded drag surfaces must call the same Loader reorder contract.",
);
assert.match(
  widgetSource,
  /const liveDescriptor = hmbVideoPickerPreviewDescriptor\(currentWidgetState\(\), container\);[\s\S]*?stageRequestedPreviewSource\(true, retryUid, retryUrl\)/,
  "Retry must resolve the current Loader item instead of a stale render closure.",
);
assert.match(widgetSource, /container\.__hmbPickerPreviewRequestToken === requestToken/);
assert.match(widgetSource, /requestAnimationFrame\(runStartPreview\)/);
assert.match(widgetSource, /hmbStagePickerViewportVideoSource\([\s\S]*?requestToken,\s*\);/);
assert.match(widgetSource, /const cancelProbe = \(\) => \{/);
assert.match(widgetSource, /retainedMarker\.token = requestToken;[\s\S]*?retainedMarker\.source = requestedUrl/);
assert.doesNotMatch(
  widgetSource.slice(
    widgetSource.indexOf("function hmbVideoPickerSourceSwapPauseMarker"),
    widgetSource.indexOf("export function hmbBeginVideoPickerPlaybackIntent"),
  ),
  /expiresAtMs|expiryTimer/,
  "Queued media pause ownership must be event-driven, not lost during a long UI stall.",
);

// Generation + exact-media identity is the shared guard for both playback
// surfaces. A callback from A cannot cancel the newer B intent.
{
  const container = {};
  const media = {};
  const first = widget.hmbBeginVideoPickerPlaybackIntent(container, media, "video-a", "card");
  const second = widget.hmbBeginVideoPickerPlaybackIntent(container, media, "video-b", "card");
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, media, first), false);
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, media, second), true);
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, media, "video-b"), true);
  assert.equal(widget.hmbCancelVideoPickerPlaybackIntent(container, {}), false);
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, media, second), true);
  assert.equal(widget.hmbCancelVideoPickerPlaybackIntent(container, media), true);
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, media, second), false);
}

class FakeVideo {
  constructor(source = "") {
    this.attributes = new Map(source ? [["src", source]] : []);
    this.listeners = new Map();
    this.paused = true;
    this.ended = false;
    this.hidden = false;
    this.readyState = 2;
    this.currentTime = 0;
    this.currentSrc = source;
    this.error = null;
    this.playCalls = 0;
    this.pauseCalls = 0;
  }
  getAttribute(name) { return this.attributes.get(name) ?? null; }
  setAttribute(name, value) {
    this.attributes.set(name, String(value));
    if (name === "src") this.currentSrc = String(value);
  }
  addEventListener(type, handler) {
    if (!this.listeners.has(type)) this.listeners.set(type, []);
    this.listeners.get(type).push(handler);
  }
  removeEventListener(type, handler) {
    this.listeners.set(type, (this.listeners.get(type) || []).filter((item) => item !== handler));
  }
  dispatch(type) { for (const handler of this.listeners.get(type) || []) handler({ type, target: this }); }
  play() { this.playCalls += 1; this.paused = false; return Promise.resolve(); }
  pause() { this.pauseCalls += 1; this.paused = true; }
}

// Compact Transport Pause must complete before any full Picker normalization or
// host publication. DOM replacement is irrelevant: the retained player UID is
// the media identity.
{
  const video = new FakeVideo("/external/video-b.mp4");
  video.paused = false;
  video.setAttribute("data-video-uid", "video-b");
  const buttons = ["video-a", "video-b"].map((uid) => ({
    attributes: new Map([
      ["data-play-video-uid", uid],
      ["data-video-title", uid],
    ]),
    textContent: uid === "video-b" ? "Ⅱ" : "▶",
    getAttribute(name) { return this.attributes.get(name) ?? null; },
    setAttribute(name, value) { this.attributes.set(name, String(value)); },
    closest() { return { classList: { toggle() {} } }; },
  }));
  const container = {
    __hmbVideoPickerExpanded: false,
    __hmbCompactSharedVideoPlayer: video,
    querySelectorAll(selector) { return selector === "[data-play-video-uid]" ? buttons : []; },
    querySelector() { return null; },
  };
  widget.hmbBeginVideoPickerPlaybackIntent(container, video, "video-b", "card");
  assert.equal(widget.hmbPauseVideoPickerCompactPlayerNow(container, "video-b"), true);
  assert.equal(video.pauseCalls, 1);
  assert.equal(video.paused, true);
  assert.ok(buttons.every((button) => button.textContent === "▶"));
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, video, "video-b"), false);
  container.__hmbVideoPickerExpanded = true;
  video.paused = false;
  assert.equal(widget.hmbPauseVideoPickerCompactPlayerNow(container, "video-b"), false);
  assert.equal(video.pauseCalls, 1, "Expanded playback is outside the compact Pause path.");
}

// The expanded viewport consumes exactly one old-source pause during a source
// swap. Every later/user pause is authoritative and must stop immediately.
{
  const video = new FakeVideo("/external/video-a.mp4");
  video.setAttribute("data-video-uid", "video-a");
  const container = {
    __hmbVideoPickerExpanded: true,
    querySelector(selector) { return selector === "#picker-video" ? video : null; },
    querySelectorAll() { return []; },
  };
  const controller = widget.hmbCreateVideoPickerMediaController(container, {
    state: loaderState("video-a"),
  });
  assert.equal(controller.togglePlayback(), true);
  assert.equal(video.playCalls, 1);
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, video, "video-a"), true);
  video.paused = true;
  video.dispatch("pause");
  assert.equal(video.playCalls, 1, "A real pause must never start an automatic replay loop.");
  assert.equal(widget.hmbVideoPickerPlaybackIntentMatches(container, video, "video-a"), false);

  const nextIntent = widget.hmbBeginVideoPickerPlaybackIntent(
    container,
    video,
    "video-b",
    "viewport",
    { ignoreNextPause: 1 },
  );
  video.setAttribute("src", "/external/video-b.mp4");
  video.setAttribute("data-video-uid", "video-b");
  controller.refresh(loaderState("video-b"));
  video.paused = true;
  video.dispatch("pause");
  assert.equal(
    widget.hmbVideoPickerPlaybackIntentMatches(container, video, nextIntent),
    true,
    "Only the one delayed pause caused by source replacement may be ignored.",
  );
  assert.equal(video.playCalls, 1, "Ignoring a source-swap pause must not call play twice.");
  video.paused = false;
  video.dispatch("play");
  video.paused = true;
  video.dispatch("pause");
  assert.equal(
    widget.hmbVideoPickerPlaybackIntentMatches(container, video, nextIntent),
    false,
    "The pause allowance must be cleared once replacement playback starts.",
  );

  const cardMedia = {};
  container.__hmbVideoPickerExpanded = false;
  const cardIntent = widget.hmbBeginVideoPickerPlaybackIntent(
    container,
    cardMedia,
    "video-b",
    "card",
  );
  video.dispatch("pause");
  assert.equal(
    widget.hmbVideoPickerPlaybackIntentMatches(container, cardMedia, cardIntent),
    true,
    "A detached expanded player must not clear compact card playback.",
  );
  controller.cleanup();
}

// A staged expanded source replacement marks its delayed old-source pause so
// the new playback intent can consume that event once, without replay loops.
{
  const probeListeners = new Map();
  const probe = {
    addEventListener(type, handler) { probeListeners.set(type, handler); },
    removeEventListener(type, handler) {
      if (probeListeners.get(type) === handler) probeListeners.delete(type);
    },
    removeAttribute() {},
    load() {},
  };
  const video = new FakeVideo("/external/video-a.mp4");
  video.paused = false;
  video.ended = false;
  video.load = () => {};
  video.closest = () => null;
  video.ownerDocument = { createElement: (tag) => (tag === "video" ? probe : null) };
  video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
  const cleanup = [];
  let readyCalls = 0;
  assert.equal(widget.hmbStagePickerViewportVideoSource(
    video,
    cleanup,
    () => { readyCalls += 1; },
  ), true);
  probeListeners.get("loadeddata")?.();
  assert.equal(video.getAttribute("src"), "/external/video-b.mp4");
  assert.equal(video.__hmbPickerSourceSwapPausePending.source, "/external/video-b.mp4");
  assert.equal(video.__hmbPickerSourceSwapPausePending.pauseDebt, 1);
  assert.equal(readyCalls, 1);
  assert.equal(widget.hmbConsumeVideoPickerPauseDebt(video), true);
  assert.equal(video.__hmbPickerSourceSwapPausePending, undefined);
  cleanup.forEach((dispose) => dispose());
  assert.equal(video.__hmbPickerSourceSwapPausePending, undefined);
}

// If stage B supersedes stage A before A's queued pause arrives, B inherits the
// one media pause debt even though its destination URL differs.
{
  const probes = [];
  const makeProbe = () => {
    const listeners = new Map();
    const probe = {
      listeners,
      addEventListener(type, handler) { listeners.set(type, handler); },
      removeEventListener(type, handler) {
        if (listeners.get(type) === handler) listeners.delete(type);
      },
      removeAttribute() {},
      load() {},
    };
    probes.push(probe);
    return probe;
  };
  const video = new FakeVideo("/external/video-a.mp4");
  video.paused = false;
  video.load = () => {};
  video.closest = () => null;
  video.ownerDocument = { createElement: makeProbe };
  const tokenA = { mountGeneration: 3, sequence: 1 };
  video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
  const cleanupA = [];
  widget.hmbStagePickerViewportVideoSource(video, cleanupA, () => {}, () => {}, tokenA);
  probes[0].listeners.get("loadeddata")?.();
  assert.equal(video.__hmbPickerSourceSwapPausePending.pauseDebt, 1);

  const tokenB = { mountGeneration: 3, sequence: 2 };
  video.__hmbPendingPickerVideoSource = "/external/video-c.mp4";
  const cleanupB = [];
  widget.hmbStagePickerViewportVideoSource(video, cleanupB, () => {}, () => {}, tokenB);
  probes[1].listeners.get("loadeddata")?.();
  assert.equal(video.getAttribute("src"), "/external/video-c.mp4");
  assert.equal(video.__hmbPickerSourceSwapPausePending.pauseDebt, 1);
  assert.equal(video.__hmbPickerSourceSwapPausePending.token, tokenB);
  assert.equal(video.__hmbPickerSourceSwapPausePending.source, "/external/video-c.mp4");
  assert.equal(widget.hmbConsumeVideoPickerPauseDebt(video), true);
  cleanupA.concat(cleanupB).forEach((dispose) => dispose());
}

// Cancelling a pending Retry owns the RAF and source-swap marker as one unit.
{
  const token = { mountGeneration: 7 };
  const media = { __hmbPickerSourceSwapPausePending: { source: "/a.mp4", token } };
  const cancelled = [];
  const previousCancelAnimationFrame = globalThis.cancelAnimationFrame;
  globalThis.cancelAnimationFrame = (handle) => { cancelled.push(handle); };
  try {
    const container = {
      __hmbPickerPreviewRequestToken: token,
      __hmbAutoplayVideoUid: "video-a",
      __hmbPickerPreviewPlaybackFrames: new Set([17]),
      querySelectorAll: () => [media],
    };
    assert.equal(widget.hmbCancelVideoPickerPendingPreviewStart(container), true);
    assert.deepEqual(cancelled, [17]);
    assert.equal(container.__hmbPickerPreviewRequestToken, undefined);
    assert.equal(container.__hmbAutoplayVideoUid, undefined);
    assert.equal(container.__hmbPickerPreviewPlaybackFrames.size, 0);
    assert.equal(media.__hmbPickerSourceSwapPausePending, undefined);
  } finally {
    if (previousCancelAnimationFrame === undefined) delete globalThis.cancelAnimationFrame;
    else globalThis.cancelAnimationFrame = previousCancelAnimationFrame;
  }
}

// Cancelling while the preload probe is still pending must make its late
// loadeddata event inert; it cannot replace the media source after Pause/mode switch.
{
  const probeListeners = new Map();
  const probe = {
    addEventListener(type, handler) { probeListeners.set(type, handler); },
    removeEventListener(type, handler) {
      if (probeListeners.get(type) === handler) probeListeners.delete(type);
    },
    removeAttribute() {},
    load() {},
  };
  const video = new FakeVideo("/external/video-a.mp4");
  video.load = () => {};
  video.closest = () => null;
  video.ownerDocument = { createElement: () => probe };
  video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
  const token = { mountGeneration: 9 };
  const cleanup = [];
  let readyCalls = 0;
  widget.hmbStagePickerViewportVideoSource(
    video,
    cleanup,
    () => { readyCalls += 1; },
    () => {},
    token,
  );
  const staleLoadedData = probeListeners.get("loadeddata");
  const container = {
    __hmbPickerPreviewRequestToken: token,
    __hmbAutoplayVideoUid: "video-b",
    __hmbPickerPreviewPlaybackFrames: new Set(),
    querySelectorAll: () => [video],
  };
  assert.equal(widget.hmbCancelVideoPickerPendingPreviewStart(container), true);
  staleLoadedData?.();
  assert.equal(video.getAttribute("src"), "/external/video-a.mp4");
  assert.equal(video.__hmbPendingPickerVideoSource, undefined);
  assert.equal(video.__hmbPickerCancelProbe, undefined);
  assert.equal(readyCalls, 0);
  cleanup.forEach((dispose) => dispose());
}

// If B is already applied and only its autoplay RAF is pending, Pause must
// retire the request token too; there is no live probe left to release it.
{
  const token = {
    mountGeneration: 10,
    sequence: 2,
    uid: "video-b",
    url: "/external/video-b.mp4",
  };
  const video = new FakeVideo("/external/video-b.mp4");
  const container = {
    __hmbPickerPreviewRequestToken: token,
    __hmbAutoplayVideoUid: "video-b",
    __hmbPickerPreviewPlaybackFrames: new Set(),
    querySelector(selector) { return selector === "#picker-video" ? video : null; },
  };
  assert.equal(widget.hmbCancelVideoPickerPendingPreviewStart(
    container,
    { preserveSourceProbe: true },
  ), true);
  assert.equal(container.__hmbPickerPreviewRequestToken, undefined);
  assert.equal(container.__hmbAutoplayVideoUid, undefined);
  assert.equal(video.getAttribute("src"), "/external/video-b.mp4");
}

// Transport Pause is different from a mode switch or cleanup: it cancels only
// autoplay and leaves the selected Loader card's source probe alive. A second
// Play re-arms B and must never replay retained source A under B's card state.
{
  const token = {
    mountGeneration: 11,
    sequence: 1,
    uid: "video-b",
    url: "/external/video-b.mp4",
  };
  const video = new FakeVideo("/external/video-a.mp4");
  video.paused = false;
  video.setAttribute("data-video-uid", "video-b");
  let probeCancellations = 0;
  video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
  video.__hmbPickerCancelProbe = () => { probeCancellations += 1; };
  const container = {
    __hmbVideoPickerExpanded: true,
    __hmbPickerPreviewRequestToken: token,
    __hmbAutoplayVideoUid: "video-b",
    __hmbPickerPreviewPlaybackFrames: new Set(),
    querySelector(selector) { return selector === "#picker-video" ? video : null; },
    querySelectorAll() { return [video]; },
  };
  const controller = widget.hmbCreateVideoPickerMediaController(container, {
    state: loaderState("video-b"),
  });
  assert.equal(controller.togglePlayback(), true);
  assert.equal(video.pauseCalls, 1);
  assert.equal(video.playCalls, 0);
  assert.equal(probeCancellations, 0);
  assert.equal(container.__hmbPickerPreviewRequestToken, token);
  assert.equal(video.__hmbPendingPickerVideoSource, "/external/video-b.mp4");
  assert.equal(container.__hmbAutoplayVideoUid, undefined);

  assert.equal(controller.togglePlayback(), true);
  assert.equal(video.playCalls, 0, "Retained A must not play while B is still staging.");
  assert.equal(container.__hmbAutoplayVideoUid, "video-b");
  assert.equal(container.__hmbPickerPreviewRequestToken, token);
  controller.cleanup();
}

// Canvas motion may suspend a B probe while retained A was playing. Motion end
// resumes the B probe but must not briefly call play() on A.
{
  const video = new FakeVideo("/external/video-a.mp4");
  video.paused = false;
  let resumed = 0;
  video.__hmbPickerSuspendProbe = () => {
    video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
    video.__hmbPickerResumeProbe = () => { resumed += 1; };
  };
  const root = {
    setAttribute() {},
    querySelectorAll() { return [video]; },
  };
  const container = {
    querySelector(selector) { return selector === ".hmbvp" ? root : null; },
  };
  assert.equal(widget.hmbSetVideoPickerCanvasMotion(container, true), true);
  assert.equal(video.pauseCalls, 1);
  assert.equal(widget.hmbSetVideoPickerCanvasMotion(container, false), true);
  assert.equal(resumed, 1);
  assert.equal(video.playCalls, 0, "Pending B must own resume; retained A cannot flash.");
  assert.equal(widget.hmbConsumeVideoPickerPauseDebt(video), true);
}

// A canvas-motion suspension may be followed by full cancellation. The latter
// must still remove the suspended resume hook and its pending source.
{
  const probeListeners = new Map();
  const probe = {
    addEventListener(type, handler) { probeListeners.set(type, handler); },
    removeEventListener(type, handler) {
      if (probeListeners.get(type) === handler) probeListeners.delete(type);
    },
    removeAttribute() {},
    load() {},
  };
  const video = new FakeVideo("/external/video-a.mp4");
  video.load = () => {};
  video.closest = () => null;
  video.ownerDocument = { createElement: () => probe };
  video.__hmbPendingPickerVideoSource = "/external/video-b.mp4";
  const cleanup = [];
  widget.hmbStagePickerViewportVideoSource(video, cleanup, () => {}, () => {});
  const cancelProbe = video.__hmbPickerCancelProbe;
  video.__hmbPickerSuspendProbe();
  assert.equal(typeof video.__hmbPickerResumeProbe, "function");
  cancelProbe();
  assert.equal(video.__hmbPendingPickerVideoSource, undefined);
  assert.equal(video.__hmbPickerCancelProbe, undefined);
  assert.equal(video.__hmbPickerResumeProbe, undefined);
  cleanup.forEach((dispose) => dispose());
}

const failedSwitchStart = widgetSource.indexOf("const failRequestedPreviewSwitch = (");
const failedSwitchEnd = widgetSource.indexOf("const stageRequestedPreviewSource = (", failedSwitchStart);
const failedSwitchSource = widgetSource.slice(failedSwitchStart, failedSwitchEnd);
assert.match(failedSwitchSource, /hmbVideoPickerRequestedPlaybackUid\(container\) === requestedUid/);
assert.match(failedSwitchSource, /hmbCancelVideoPickerPlaybackIntent\(container\)/);
assert.match(failedSwitchSource, /hmbSyncVideoPickerPlayButtonState\(container, "", false, tr\)/);

class FakePoster {
  constructor(parent = null) {
    this.attributes = new Map();
    this.hidden = true;
    this.currentSrc = "";
    this.parentElement = parent;
  }
  getAttribute(name) { return this.attributes.get(name) ?? null; }
  setAttribute(name, value) {
    this.attributes.set(name, String(value));
    if (name === "src") this.currentSrc = String(value);
  }
  removeAttribute(name) {
    this.attributes.delete(name);
    if (name === "src") this.currentSrc = "";
  }
  cloneNode() {
    const clone = new FakePoster(this.parentElement);
    clone.attributes = new Map(this.attributes);
    clone.hidden = this.hidden;
    clone.currentSrc = this.currentSrc;
    return clone;
  }
  replaceWith(replacement) {
    if (this.parentElement) {
      this.parentElement.poster = replacement;
      replacement.parentElement = this.parentElement;
    }
    this.parentElement = null;
  }
}
class FakeThumb {
  constructor(source, suppliedPoster = "") {
    this.attributes = new Map([["data-compact-thumbnail-source", source]]);
    if (suppliedPoster) this.attributes.set("data-compact-thumbnail-poster", suppliedPoster);
    this.poster = new FakePoster(this);
    this.placeholder = { hidden: false };
    this.classList = { add() {}, remove() {} };
  }
  getAttribute(name) { return this.attributes.get(name) ?? null; }
  setAttribute(name, value) { this.attributes.set(name, String(value)); }
  removeAttribute(name) { this.attributes.delete(name); }
  querySelector(selector) {
    if (selector === ".compact-video-poster") return this.poster;
    if (selector === ".compact-shot-placeholder") return this.placeholder;
    return null;
  }
}

// A backend-generated poster is the primary path. It must skip the browser
// video/canvas probe entirely and still reveal the image immediately.
{
  let videoCreates = 0;
  const thumb = new FakeThumb("/external/a.mp4", "/static/a-poster.png");
  const ownerDocument = {
    defaultView: {},
    createElement(tag) {
      if (tag === "video") videoCreates += 1;
      return {};
    },
  };
  const container = {
    ownerDocument,
    __hmbVideoPickerExpanded: false,
    querySelectorAll(selector) {
      return selector === "[data-compact-thumbnail-source]" ? [thumb] : [];
    },
  };
  assert.equal(widget.hmbSyncVideoPickerCompactThumbnails(container), 1);
  assert.equal(videoCreates, 0);
  assert.equal(thumb.poster.getAttribute("src"), "/static/a-poster.png");
  assert.equal(thumb.poster.hidden, false);
  assert.equal(thumb.placeholder.hidden, true);
  widget.hmbDisposeVideoPickerCompactThumbnailController(container);
}

// A late backend poster must cancel the in-flight browser decoder. A failed
// poster URL is quarantined so subsequent state patches use the browser fallback
// instead of repeatedly flashing the same broken image.
{
  let releasedProbes = 0;
  class ImmediateObserver {
    constructor(callback) { this.callback = callback; }
    observe(target) { this.callback([{ target, isIntersecting: true }]); }
    unobserve() {}
    disconnect() {}
  }
  const thumb = new FakeThumb("/external/late.mp4");
  const probe = {
    pause() {},
    removeAttribute(name) { if (name === "src") releasedProbes += 1; },
    load() {},
    setAttribute() {},
  };
  const ownerDocument = {
    defaultView: { IntersectionObserver: ImmediateObserver },
    createElement(tag) { return tag === "video" ? probe : {}; },
  };
  const container = {
    ownerDocument,
    __hmbVideoPickerExpanded: false,
    querySelectorAll(selector) {
      return selector === "[data-compact-thumbnail-source]" ? [thumb] : [];
    },
  };
  const controller = widget.hmbEnsureVideoPickerCompactThumbnailController(container);
  controller.sync();
  assert.equal(controller.applyServerPoster(thumb, "/static/late.png"), true);
  assert.equal(releasedProbes, 1, "Late server poster must release the active video probe.");
  const oldPosterElement = thumb.poster;
  assert.equal(controller.applyServerPoster(thumb, "/static/replacement.png"), true);
  assert.notEqual(thumb.poster, oldPosterElement, "Poster URL changes must replace the image element.");
  assert.equal(oldPosterElement.parentElement, null, "A late error from the old request is detached.");
  assert.equal(controller.markServerPosterFailed(thumb, "/static/replacement.png"), true);
  assert.equal(controller.applyServerPoster(thumb, "/static/replacement.png"), false);
  assert.equal(thumb.getAttribute("data-compact-thumbnail-poster"), null);
  assert.equal(controller.applyServerPoster(thumb, "/static/new.png"), true);
  controller.dispose();
}

assert.match(
  widgetSource,
  /const dueSources = \[\];[\s\S]*?container\.__hmbVideoPickerExpanded === true \|\| !targets\.length[\s\S]*?for \(const thumb of targets\) enqueue\(thumb\);/,
  "IntersectionObserver thumbnail failures must enqueue a real timed retry.",
);
assert.match(
  widgetSource,
  /let nextHandle = null;[\s\S]*?if \(nextHandle != null\) return;[\s\S]*?nextHandle = setTimeout/,
  "Thumbnail queue wakeups must be coalesced instead of scheduling one timer per card.",
);

// Two visible cards are decoded serially through fresh, immediately released
// probes. This guards against both stale media events and 10–50 live decoders.
{
  let videoCreates = 0;
  let canvasCreates = 0;
  let activeProbes = 0;
  let maxActiveProbes = 0;
  const probeTrace = [];
  class ImmediateObserver {
    constructor(callback) { this.callback = callback; }
    observe(target) { this.callback([{ target, isIntersecting: true }]); }
    unobserve() {}
    disconnect() {}
  }
  class Probe {
    constructor() {
      this.attributes = new Map();
      this.muted = false;
      this.playsInline = false;
      this.preload = "none";
      this.readyState = 0;
      this.duration = 2;
      this.videoWidth = 1920;
      this.videoHeight = 1080;
      this._currentTime = 0;
      this._src = "";
      this.started = false;
      this.released = false;
    }
    set currentTime(value) {
      this._currentTime = value;
      this.onseeked?.();
    }
    get currentTime() { return this._currentTime; }
    set src(value) { this._src = String(value); }
    get src() { return this._src; }
    setAttribute(name, value) {
      this.attributes.set(name, String(value));
      if (name === "src") this._src = String(value);
    }
    removeAttribute(name) {
      this.attributes.delete(name);
      if (name === "src") {
        this._src = "";
        if (this.started && !this.released) {
          this.released = true;
          activeProbes -= 1;
          probeTrace.push(`end:${this.source}`);
        }
      }
    }
    load() {
      const source = this.attributes.get("src");
      if (!source) return;
      if (!this.started) {
        this.started = true;
        this.source = source;
        activeProbes += 1;
        maxActiveProbes = Math.max(maxActiveProbes, activeProbes);
        probeTrace.push(`start:${source}`);
      }
      // Match browser ordering: metadata has no decoded frame yet; loadeddata
      // makes the first frame available even if an early seeked already fired.
      this.readyState = 1;
      this.onloadedmetadata?.();
      this.readyState = 2;
      this.onloadeddata?.();
    }
    pause() {}
  }
  const ownerDocument = {
    defaultView: { IntersectionObserver: ImmediateObserver },
    createElement(tag) {
      if (tag === "video") { videoCreates += 1; return new Probe(); }
      if (tag === "canvas") {
        canvasCreates += 1;
        return {
          width: 0,
          height: 0,
          getContext: () => ({ fillStyle: "", fillRect() {}, drawImage() {} }),
          toDataURL: () => `data:image/webp;base64,poster-${canvasCreates}`,
        };
      }
      throw new Error(`Unexpected element: ${tag}`);
    },
  };
  const thumbs = [new FakeThumb("/external/a.mp4"), new FakeThumb("/external/b.mp4")];
  const container = {
    ownerDocument,
    __hmbVideoPickerExpanded: false,
    querySelectorAll(selector) {
      return selector === "[data-compact-thumbnail-source]" ? thumbs : [];
    },
  };
  assert.equal(widget.hmbSyncVideoPickerCompactThumbnails(container), 2);
  await new Promise((resolve) => setTimeout(resolve, 20));
  assert.equal(videoCreates, 2);
  assert.equal(canvasCreates, 2);
  assert.equal(maxActiveProbes, 1);
  assert.deepEqual(probeTrace, [
    "start:/external/a.mp4",
    "end:/external/a.mp4",
    "start:/external/b.mp4",
    "end:/external/b.mp4",
  ]);
  assert.ok(thumbs.every((thumb) => thumb.poster.getAttribute("src")?.startsWith("data:image/webp")));
  assert.ok(thumbs.every((thumb) => thumb.poster.hidden === false && thumb.placeholder.hidden === true));
  widget.hmbDisposeVideoPickerCompactThumbnailController(container);
}

console.log("HMB VideoPicker unified Loader playback and lazy-thumbnail regression: PASS");
